# Snowflake Snowpark Project Configuration Template
# Copy this file to Snowflake_Snowpark_1sttry_config.toml and fill in your credentials.
# DO NOT COMMIT your real credentials to version control!

[snowflake]
account = "<your_account>"
user = "<your_user>"
password = "<your_password>"
role = "<your_role>"
warehouse = "<your_warehouse>"
database = "<your_database>"
schema = "<your_schema>" 